### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by Zero3K** [Loading617/Shine#1]
*subject*

**Comment by Loading617** [comment]
It's coming man!!

**Comment by Zero3K** [comment]
Will it be in C/C++ or something else?

**Comment by Loading617** [comment]
Yes and Java

**Comment by Zero3K** [comment]
Okay. I hope it can play the Rockman EXE mobile games (Phantom of Network and Legend of Network).

**Comment by Loading617** [comment]
It will man!!

**Comment by Zero3K** [comment]
Why was this marked as completed?

**Comment by Loading617** [comment]
You have more concerns?

**Comment by Zero3K** [comment]
No.
